
[package]
edition.workspace = true
name = "bee-miner"
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["ackinacki-kit/default"]
wasm = [
    "dep:wasm-bindgen",
    "dep:serde-wasm-bindgen",
    "dep:js-sys",
    "bee-infra/wasm",
    "ackinacki-kit/wasm",
]
single-wasm = ["wasm"]

[dependencies]
ackinacki-kit = { git = "https://github.com/gosh-sh/ackinacki-kit.git", rev = "2ff066244a59f3ab7f2fa017a8b3390cdd3e8186", default-features = false, features = ["contracts"] }
base64 = "0.22.1"
blake3.workspace = true
borsh.workspace = true
futures = "0.3.31"
gloo-timers = { version = "0.3.0", features = ["futures"] }
hex.workspace = true
js-sys = { optional = true, version = "0.3.83" }
rs_merkle.workspace = true
bee-shared = { path = "../bee_shared" }
bee-infra = { path = "../bee_infra", default-features = false, features = ["tokio"] }
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.17"
wasm-bindgen = { optional = true, version = "0.2.106", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.56"
serde-wasm-bindgen = { optional = true, version = "0.6.5" }
web-sys = { version = "0.3.83", features = ["console"] }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt", "macros"] }
wasm-bindgen-test = "0.3.56"
