[package]
name = "bee-infra"
version.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["ackinacki-kit?/default"]
message-delivery = ["dep:ackinacki-kit", "dep:async-trait", "dep:serde_json"]
wasm = ["dep:gloo-timers", "dep:js-sys", "ackinacki-kit?/wasm"]
tokio = ["dep:tokio"]

[dependencies]
ackinacki-kit = { git = "https://github.com/gosh-sh/ackinacki-kit.git", rev = "2ff066244a59f3ab7f2fa017a8b3390cdd3e8186", optional = true, default-features = false, features = ["contracts"] }
async-trait = { version = "0.1", optional = true }
gloo-timers = { version = "0.3.0", features = ["futures"], optional = true }
js-sys = { version = "0.3.83", optional = true }
parking_lot = "0.12"
serde_json = { workspace = true, optional = true }
tokio = { version = "1.49.0", features = ["time"], optional = true }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt", "macros", "time"] }
wasm-bindgen-test = "0.3"
